fix: frontend workflow test new

diff --git a/.github/workflows/workflow-dev.yml b/.github/workflows/workflow-dev.yml
--- a/.github/workflows/workflow-dev.yml
+++ b/.github/workflows/workflow-dev.yml
@@ -59,48 +59,48 @@ jobs:
           sleep 20 
           curl --retry 10 --retry-delay 5 --retry-all-errors -I http://localhost:8088 || (echo "Backend failed to start" && exit 1)
 
-build_and_test_frontend:
-  runs-on: ubuntu-latest
-  steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+  build_and_test_frontend:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: 20
-        cache: "npm"
-        cache-dependency-path: frontend/package-lock.json
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+          cache: "npm"
+          cache-dependency-path: frontend/package-lock.json
 
-    - name: Install Dependencies
-      run: |
-        cd frontend
-        npm install
+      - name: Install Dependencies
+        run: |
+          cd frontend
+          npm install
 
-    - name: Install Playwright Browsers
-      run: |
-        cd frontend
-        npx playwright install --with-deps
+      - name: Install Playwright Browsers
+        run: |
+          cd frontend
+          npx playwright install --with-deps
 
-    - name: Start Backend
-      run: |
-        cd restaurant
-        nohup mvn spring-boot:run > backend.log 2>&1 &  
-        sleep 40  
-        curl --retry 10 --retry-delay 5 --retry-all-errors -I http://localhost:8088 || (echo "Backend failed to start" && exit 1)
+      - name: Start Backend
+        run: |
+          cd restaurant
+          nohup mvn spring-boot:run > backend.log 2>&1 &  
+          sleep 40  
+          curl --retry 10 --retry-delay 5 --retry-all-errors -I http://localhost:8088 || (echo "Backend failed to start" && exit 1)
 
-    - name: Start Frontend
-      run: |
-        cd frontend
-        nohup npm run dev -- --host > frontend.log 2>&1 &
-        sleep 10  
+      - name: Start Frontend
+        run: |
+          cd frontend
+          nohup npm run dev -- --host > frontend.log 2>&1 &
+          sleep 10  
 
-    - name: Run Playwright Tests
-      run: |
-        cd frontend
-        npx playwright test
+      - name: Run Playwright Tests
+        run: |
+          cd frontend
+          npx playwright test
 
-    - name: Build Vue.js Frontend
-      run: |
-        cd frontend
-        npm run build
+      - name: Build Vue.js Frontend
+        run: |
+          cd frontend
+          npm run build
